const { getDb } = require('./database');

// 140 menu entries from Menus_10_Semanas_Comidas_Cenas_para_ClaudeCode.md
// meal_type: 'lunch' | 'dinner'
const WEEKLY_MENUS = [
  // ── Semana 1 ──────────────────────────────────────────────────────────────
  { w: 1, day: 'Lunes', type: 'lunch', name: 'Pollo a la plancha con arroz y verduras',
    ing: ['pollo','arroz','calabacín','zanahoria','cebolla','aceite de oliva','ajo'],
    steps: ['Cuece el arroz en agua con sal.','Corta las verduras en dados y saltéalas con aceite.','Cocina el pollo a la plancha con sal, pimienta y ajo.','Sirve el arroz con las verduras y el pollo encima.'] },
  { w: 1, day: 'Lunes', type: 'dinner', name: 'Crema de calabacín con tortilla francesa',
    ing: ['calabacín','patata','cebolla','huevo','aceite'],
    steps: ['Cuece calabacín, patata y cebolla.','Tritura con agua de cocción y sal.','Bate el huevo y haz una tortilla francesa.','Sirve la crema con la tortilla al lado.'] },
  { w: 1, day: 'Martes', type: 'lunch', name: 'Lentejas con verduras',
    ing: ['lentejas','zanahoria','pimiento','cebolla','tomate','laurel','pimentón','aceite'],
    steps: ['Sofríe cebolla, pimiento y zanahoria.','Añade tomate, pimentón y laurel.','Incorpora las lentejas y cubre con agua.','Cocina hasta que estén tiernas.'] },
  { w: 1, day: 'Martes', type: 'dinner', name: 'Ensalada de atún y huevo',
    ing: ['lechuga','tomate','huevo','atún','maíz','aceitunas','aceite','vinagre'],
    steps: ['Cuece el huevo 10 minutos.','Lava y corta lechuga y tomate.','Añade atún, maíz, aceitunas y huevo troceado.','Aliña con aceite, vinagre y sal.'] },
  { w: 1, day: 'Miércoles', type: 'lunch', name: 'Pasta con tomate, verduras y queso',
    ing: ['pasta','tomate','berenjena o calabacín','cebolla','queso rallado','aceite','orégano'],
    steps: ['Cuece la pasta.','Sofríe cebolla y verdura en dados.','Añade tomate triturado, sal y orégano.','Mezcla con la pasta y termina con queso rallado.'] },
  { w: 1, day: 'Miércoles', type: 'dinner', name: 'Merluza al horno con patata',
    ing: ['merluza','patata','cebolla','limón','aceite','perejil'],
    steps: ['Corta la patata y cebolla en rodajas finas.','Hornéalas con aceite y sal 20 minutos.','Añade la merluza, limón y perejil.','Hornea 10-12 minutos más.'] },
  { w: 1, day: 'Jueves', type: 'lunch', name: 'Garbanzos salteados con espinacas',
    ing: ['garbanzos','espinacas','ajo','cebolla','pimentón','aceite'],
    steps: ['Sofríe ajo y cebolla.','Añade espinacas hasta que reduzcan.','Incorpora garbanzos y pimentón.','Saltea todo junto 5 minutos.'] },
  { w: 1, day: 'Jueves', type: 'dinner', name: 'Sándwich integral de pavo y queso',
    ing: ['pan integral','pavo','queso','tomate','lechuga','aceite'],
    steps: ['Monta el sándwich con pavo, queso, tomate y lechuga.','Tuéstalo si quieres.','Acompaña con ensalada de lechuga y tomate.'] },
  { w: 1, day: 'Viernes', type: 'lunch', name: 'Salmón con cous cous y brócoli',
    ing: ['salmón','cous cous','brócoli','limón','aceite'],
    steps: ['Hidrata el cous cous con agua caliente y sal.','Cuece o saltea el brócoli.','Cocina el salmón a la plancha con limón.','Sirve todo junto.'] },
  { w: 1, day: 'Viernes', type: 'dinner', name: 'Revuelto de champiñones',
    ing: ['huevos','champiñones','ajo','perejil','aceite','pan integral'],
    steps: ['Saltea los champiñones con ajo.','Bate los huevos con sal.','Añádelos a la sartén y remueve hasta cuajar.','Sirve con pan integral.'] },
  { w: 1, day: 'Sábado', type: 'lunch', name: 'Arroz con pollo y pimientos',
    ing: ['arroz','pollo','pimiento rojo','pimiento verde','cebolla','caldo','aceite','cúrcuma'],
    steps: ['Dora el pollo.','Añade cebolla y pimientos picados.','Incorpora arroz, cúrcuma y caldo.','Cocina hasta que el arroz esté hecho.'] },
  { w: 1, day: 'Sábado', type: 'dinner', name: 'Tostadas con aguacate y huevo',
    ing: ['pan','aguacate','huevo','tomate','limón'],
    steps: ['Tuesta el pan.','Machaca aguacate con limón, sal y pimienta.','Cocina el huevo a la plancha o cocido.','Monta las tostadas con aguacate, tomate y huevo.'] },
  { w: 1, day: 'Domingo', type: 'lunch', name: 'Albóndigas caseras con patatas',
    ing: ['carne picada','huevo','pan rallado','ajo','perejil','tomate','patata','aceite'],
    steps: ['Mezcla carne, huevo, ajo, perejil y pan rallado.','Forma albóndigas y dóralas.','Cocina con tomate triturado 20 minutos.','Acompaña con patatas cocidas o al horno.'] },
  { w: 1, day: 'Domingo', type: 'dinner', name: 'Ensalada templada de verduras y queso fresco',
    ing: ['calabacín','pimiento','cebolla','queso fresco','lechuga','aceite','vinagre'],
    steps: ['Saltea calabacín, pimiento y cebolla.','Coloca una base de lechuga.','Añade las verduras templadas y el queso fresco.','Aliña al gusto.'] },

  // ── Semana 2 ──────────────────────────────────────────────────────────────
  { w: 2, day: 'Lunes', type: 'lunch', name: 'Ternera guisada con verduras',
    ing: ['ternera','zanahoria','patata','cebolla','guisantes','caldo','aceite'],
    steps: ['Dora la ternera en una olla.','Añade cebolla, zanahoria y patata.','Cubre con caldo y cocina hasta que la carne esté tierna.','Añade guisantes al final.'] },
  { w: 2, day: 'Lunes', type: 'dinner', name: 'Crema de zanahoria con queso fresco',
    ing: ['zanahoria','patata','cebolla','queso fresco','aceite'],
    steps: ['Cuece zanahoria, patata y cebolla.','Tritura con un poco de caldo de cocción.','Sirve con queso fresco en dados.'] },
  { w: 2, day: 'Martes', type: 'lunch', name: 'Pasta con atún y tomate',
    ing: ['pasta','atún','tomate','cebolla','aceite','orégano'],
    steps: ['Cuece la pasta.','Sofríe cebolla y añade tomate.','Incorpora atún escurrido y orégano.','Mezcla con la pasta.'] },
  { w: 2, day: 'Martes', type: 'dinner', name: 'Tortilla de patata ligera con ensalada',
    ing: ['patata','huevos','cebolla','lechuga','tomate','aceite'],
    steps: ['Cocina la patata en rodajas.','Mezcla con huevo batido y sal.','Cuaja la tortilla por ambos lados.','Sirve con ensalada.'] },
  { w: 2, day: 'Miércoles', type: 'lunch', name: 'Garbanzos con arroz y verduras',
    ing: ['garbanzos','arroz','zanahoria','cebolla','pimiento','tomate','pimentón','aceite'],
    steps: ['Sofríe cebolla, zanahoria y pimiento.','Añade tomate y pimentón.','Incorpora garbanzos y arroz cocido.','Saltea todo junto.'] },
  { w: 2, day: 'Miércoles', type: 'dinner', name: 'Pescado blanco con verduras salteadas',
    ing: ['pescado blanco','calabacín','zanahoria','cebolla','limón','aceite'],
    steps: ['Saltea las verduras en tiras.','Cocina el pescado a la plancha con limón y sal.','Sirve el pescado sobre las verduras.'] },
  { w: 2, day: 'Jueves', type: 'lunch', name: 'Pollo al curry con arroz',
    ing: ['pollo','arroz','cebolla','leche de coco','curry','aceite'],
    steps: ['Cuece el arroz.','Dora el pollo con cebolla.','Añade curry y leche de coco.','Cocina hasta que la salsa espese.'] },
  { w: 2, day: 'Jueves', type: 'dinner', name: 'Ensalada de garbanzos',
    ing: ['garbanzos','tomate','pepino','cebolla','atún','aceite','vinagre'],
    steps: ['Lava los garbanzos.','Corta tomate, pepino y cebolla.','Añade atún o huevo cocido.','Aliña y mezcla.'] },
  { w: 2, day: 'Viernes', type: 'lunch', name: 'Merluza en salsa verde',
    ing: ['merluza','ajo','perejil','guisantes','caldo','aceite'],
    steps: ['Sofríe ajo picado.','Añade un poco de harina y caldo.','Incorpora merluza, guisantes y perejil.','Cocina tapado 8-10 minutos.'] },
  { w: 2, day: 'Viernes', type: 'dinner', name: 'Pizza casera rápida',
    ing: ['base de pizza','tomate','mozzarella','jamón cocido','champiñones','orégano'],
    steps: ['Unta tomate sobre la base.','Añade mozzarella y toppings.','Hornea hasta que el queso se funda.','Sirve caliente.'] },
  { w: 2, day: 'Sábado', type: 'lunch', name: 'Fajitas de pollo',
    ing: ['tortillas','pollo','pimiento','cebolla','tomate','especias','aceite'],
    steps: ['Corta pollo y verduras en tiras.','Saltea todo con especias.','Calienta las tortillas.','Rellena y sirve.'] },
  { w: 2, day: 'Sábado', type: 'dinner', name: 'Sopa de fideos con huevo',
    ing: ['caldo','fideos','huevo','zanahoria','puerro','sal'],
    steps: ['Calienta el caldo con verduras picadas.','Añade los fideos.','Incorpora el huevo batido o cocido.','Cocina hasta que los fideos estén hechos.'] },
  { w: 2, day: 'Domingo', type: 'lunch', name: 'Paella sencilla de verduras y pollo',
    ing: ['arroz','pollo','judías verdes','pimiento','tomate','caldo','cúrcuma','aceite'],
    steps: ['Dora el pollo.','Añade verduras y tomate.','Incorpora arroz y caldo.','Cocina sin remover hasta que el arroz esté listo.'] },
  { w: 2, day: 'Domingo', type: 'dinner', name: 'Tostas de queso fresco, tomate y jamón',
    ing: ['pan','queso fresco','tomate','jamón serrano','aceite'],
    steps: ['Tuesta el pan.','Coloca tomate en rodajas.','Añade queso fresco y jamón.','Termina con aceite de oliva.'] },

  // ── Semana 3 ──────────────────────────────────────────────────────────────
  { w: 3, day: 'Lunes', type: 'lunch', name: 'Macarrones con carne picada',
    ing: ['macarrones','carne picada','tomate','cebolla','ajo','aceite','orégano'],
    steps: ['Cuece los macarrones.','Sofríe ajo y cebolla.','Añade carne picada y después tomate.','Mezcla con la pasta.'] },
  { w: 3, day: 'Lunes', type: 'dinner', name: 'Crema de verduras variadas',
    ing: ['calabacín','zanahoria','puerro','patata','aceite'],
    steps: ['Cuece todas las verduras troceadas.','Tritura con aceite y sal.','Añade agua de cocción hasta lograr la textura deseada.'] },
  { w: 3, day: 'Martes', type: 'lunch', name: 'Ensalada de pasta con atún',
    ing: ['pasta','atún','tomate cherry','maíz','huevo','aceitunas','aceite'],
    steps: ['Cuece la pasta y enfría.','Cuece el huevo.','Mezcla pasta, atún, tomate, maíz, aceitunas y huevo.','Aliña con aceite y sal.'] },
  { w: 3, day: 'Martes', type: 'dinner', name: 'Pechuga de pollo con ensalada',
    ing: ['pollo','lechuga','tomate','zanahoria','aceite','vinagre'],
    steps: ['Cocina el pollo a la plancha.','Prepara ensalada con lechuga, tomate y zanahoria.','Aliña y sirve junto al pollo.'] },
  { w: 3, day: 'Miércoles', type: 'lunch', name: 'Judías verdes con patata y huevo',
    ing: ['judías verdes','patata','huevo','aceite','pimentón'],
    steps: ['Cuece judías y patata.','Cuece el huevo aparte.','Sirve todo con aceite y sal.','Añade pimentón si quieres más sabor.'] },
  { w: 3, day: 'Miércoles', type: 'dinner', name: 'Salmón ahumado con tostadas y ensalada',
    ing: ['salmón ahumado','pan','queso crema','lechuga','tomate','limón'],
    steps: ['Tuesta el pan.','Unta queso crema.','Añade salmón y unas gotas de limón.','Acompaña con ensalada.'] },
  { w: 3, day: 'Jueves', type: 'lunch', name: 'Arroz tres delicias casero',
    ing: ['arroz','huevo','guisantes','zanahoria','jamón cocido','aceite'],
    steps: ['Cuece el arroz y deja enfriar.','Haz una tortilla fina y córtala.','Saltea zanahoria, guisantes y jamón.','Añade arroz y tortilla.'] },
  { w: 3, day: 'Jueves', type: 'dinner', name: 'Calabacines rellenos',
    ing: ['calabacín','carne picada','cebolla','tomate','queso rallado'],
    steps: ['Parte el calabacín y vacíalo.','Sofríe el relleno con cebolla, tomate y la pulpa.','Rellena los calabacines.','Gratina con queso.'] },
  { w: 3, day: 'Viernes', type: 'lunch', name: 'Potaje de garbanzos con espinacas',
    ing: ['garbanzos','espinacas','cebolla','ajo','tomate','pimentón','aceite'],
    steps: ['Sofríe ajo y cebolla.','Añade tomate y pimentón.','Incorpora garbanzos, espinacas y agua.','Cocina 15-20 minutos.'] },
  { w: 3, day: 'Viernes', type: 'dinner', name: 'Tortilla de espinacas',
    ing: ['huevos','espinacas','ajo','aceite'],
    steps: ['Saltea espinacas con ajo.','Bate los huevos.','Mezcla y cuaja la tortilla.'] },
  { w: 3, day: 'Sábado', type: 'lunch', name: 'Hamburguesa casera con patatas al horno',
    ing: ['carne picada','pan','lechuga','tomate','queso','patata','aceite'],
    steps: ['Corta patatas y hornéalas con aceite y sal.','Cocina la hamburguesa a la plancha.','Monta con pan, lechuga, tomate y queso.','Sirve con las patatas.'] },
  { w: 3, day: 'Sábado', type: 'dinner', name: 'Ensalada caprese con pavo',
    ing: ['tomate','mozzarella','pavo','albahaca','aceite'],
    steps: ['Corta tomate y mozzarella.','Añade pavo en tiras.','Aliña con aceite, sal y albahaca.'] },
  { w: 3, day: 'Domingo', type: 'lunch', name: 'Pollo asado con verduras',
    ing: ['pollo','patata','zanahoria','cebolla','limón','aceite','romero'],
    steps: ['Coloca verduras troceadas en una bandeja.','Añade el pollo con limón, aceite, sal y romero.','Hornea hasta que esté dorado.'] },
  { w: 3, day: 'Domingo', type: 'dinner', name: 'Sopa de verduras sencilla',
    ing: ['caldo','zanahoria','puerro','calabacín','fideos'],
    steps: ['Cuece las verduras en caldo.','Añade fideos si quieres.','Cocina hasta que todo esté tierno.'] },

  // ── Semana 4 ──────────────────────────────────────────────────────────────
  { w: 4, day: 'Lunes', type: 'lunch', name: 'Cuscús con pollo y verduras',
    ing: ['cuscús','pollo','calabacín','zanahoria','cebolla','curry','aceite'],
    steps: ['Hidrata el cuscús.','Saltea pollo y verduras.','Añade especias.','Mezcla con el cuscús.'] },
  { w: 4, day: 'Lunes', type: 'dinner', name: 'Ensalada de tomate, queso y huevo',
    ing: ['tomate','queso fresco','huevo','aceitunas','aceite','orégano'],
    steps: ['Cuece el huevo.','Corta tomate y queso.','Añade huevo y aceitunas.','Aliña con aceite, sal y orégano.'] },
  { w: 4, day: 'Martes', type: 'lunch', name: 'Lasaña rápida de verduras',
    ing: ['placas de lasaña','calabacín','berenjena','tomate','queso','bechamel'],
    steps: ['Saltea las verduras.','Monta capas de pasta, tomate, verduras y queso.','Añade bechamel.','Hornea hasta gratinar.'] },
  { w: 4, day: 'Martes', type: 'dinner', name: 'Merluza a la plancha con ensalada',
    ing: ['merluza','lechuga','tomate','pepino','limón','aceite'],
    steps: ['Cocina la merluza a la plancha.','Prepara ensalada con lechuga, tomate y pepino.','Aliña y sirve.'] },
  { w: 4, day: 'Miércoles', type: 'lunch', name: 'Alubias blancas con verduras',
    ing: ['alubias','zanahoria','cebolla','pimiento','tomate','pimentón','aceite'],
    steps: ['Sofríe verduras picadas.','Añade tomate y pimentón.','Incorpora alubias y agua.','Cocina 15 minutos.'] },
  { w: 4, day: 'Miércoles', type: 'dinner', name: 'Wrap de pollo',
    ing: ['tortilla de trigo','pollo','lechuga','tomate','yogur','limón'],
    steps: ['Cocina el pollo en tiras.','Mezcla yogur con limón y sal.','Rellena la tortilla con pollo, lechuga, tomate y salsa.','Enrolla y sirve.'] },
  { w: 4, day: 'Jueves', type: 'lunch', name: 'Bacalao con tomate',
    ing: ['bacalao','tomate','cebolla','pimiento','aceite'],
    steps: ['Sofríe cebolla y pimiento.','Añade tomate y cocina 10 minutos.','Incorpora el bacalao.','Cocina hasta que esté hecho.'] },
  { w: 4, day: 'Jueves', type: 'dinner', name: 'Revuelto de espárragos',
    ing: ['huevos','espárragos','ajo','aceite'],
    steps: ['Saltea los espárragos con ajo.','Añade huevos batidos.','Remueve hasta cuajar.'] },
  { w: 4, day: 'Viernes', type: 'lunch', name: 'Arroz con verduras y huevo frito',
    ing: ['arroz','huevo','brócoli','zanahoria','guisantes','aceite'],
    steps: ['Cuece el arroz.','Saltea verduras.','Añade arroz y soja opcional.','Sirve con huevo a la plancha encima.'] },
  { w: 4, day: 'Viernes', type: 'dinner', name: 'Crema de champiñones',
    ing: ['champiñones','cebolla','patata','caldo','leche','aceite'],
    steps: ['Sofríe cebolla y champiñones.','Añade patata y caldo.','Cuece y tritura.','Añade leche para más cremosidad.'] },
  { w: 4, day: 'Sábado', type: 'lunch', name: 'Tacos de ternera',
    ing: ['tortillas','ternera','pimiento','cebolla','tomate','especias','aceite'],
    steps: ['Saltea ternera con pimiento y cebolla.','Añade especias.','Calienta tortillas.','Rellena y sirve con tomate.'] },
  { w: 4, day: 'Sábado', type: 'dinner', name: 'Ensalada de pasta fría',
    ing: ['pasta','jamón cocido','queso','tomate','maíz','aceite'],
    steps: ['Cuece la pasta y enfría.','Añade jamón, queso, tomate y maíz.','Aliña y mezcla.'] },
  { w: 4, day: 'Domingo', type: 'lunch', name: 'Estofado de pollo con patatas',
    ing: ['pollo','patata','zanahoria','cebolla','caldo','laurel','aceite'],
    steps: ['Dora el pollo.','Añade verduras y patata.','Cubre con caldo y laurel.','Cocina hasta que esté tierno.'] },
  { w: 4, day: 'Domingo', type: 'dinner', name: 'Tortilla francesa con ensalada de aguacate',
    ing: ['huevos','aguacate','tomate','lechuga','limón','aceite'],
    steps: ['Haz una tortilla francesa.','Prepara ensalada con lechuga, tomate y aguacate.','Aliña con limón, aceite y sal.'] },

  // ── Semana 5 ──────────────────────────────────────────────────────────────
  { w: 5, day: 'Lunes', type: 'lunch', name: 'Espaguetis con gambas y ajo',
    ing: ['espaguetis','gambas','ajo','perejil','aceite'],
    steps: ['Cuece los espaguetis.','Saltea ajo y gambas.','Añade la pasta y perejil.','Mezcla bien y sirve.'] },
  { w: 5, day: 'Lunes', type: 'dinner', name: 'Crema de puerro y patata',
    ing: ['puerros','patata','cebolla','caldo','aceite'],
    steps: ['Sofríe puerro y cebolla.','Añade patata y caldo.','Cuece hasta ablandar.','Tritura y ajusta de sal.'] },
  { w: 5, day: 'Martes', type: 'lunch', name: 'Pollo con patatas al horno',
    ing: ['pollo','patatas','cebolla','limón','aceite','tomillo'],
    steps: ['Coloca patatas y cebolla en una bandeja.','Añade pollo con limón, sal y tomillo.','Hornea hasta que esté dorado.'] },
  { w: 5, day: 'Martes', type: 'dinner', name: 'Ensalada de arroz con atún',
    ing: ['arroz','atún','huevo','tomate','maíz','aceitunas','aceite'],
    steps: ['Cuece arroz y huevo.','Mezcla con atún, tomate, maíz y aceitunas.','Aliña y sirve fría.'] },
  { w: 5, day: 'Miércoles', type: 'lunch', name: 'Lentejas con arroz',
    ing: ['lentejas','arroz','zanahoria','cebolla','pimiento','tomate','pimentón','laurel'],
    steps: ['Sofríe verduras.','Añade lentejas, arroz, pimentón y laurel.','Cubre con agua.','Cocina hasta que esté tierno.'] },
  { w: 5, day: 'Miércoles', type: 'dinner', name: 'Pavo a la plancha con verduras',
    ing: ['filetes de pavo','calabacín','champiñones','cebolla','aceite'],
    steps: ['Saltea las verduras.','Cocina el pavo a la plancha.','Sirve junto con las verduras.'] },
  { w: 5, day: 'Jueves', type: 'lunch', name: 'Ensalada templada de garbanzos y pollo',
    ing: ['garbanzos','pollo','espinacas','tomate','cebolla','aceite','comino'],
    steps: ['Cocina el pollo en tiras.','Saltea garbanzos con cebolla y comino.','Añade espinacas y tomate.','Mezcla con el pollo.'] },
  { w: 5, day: 'Jueves', type: 'dinner', name: 'Tostada de hummus y verduras',
    ing: ['pan','hummus','tomate','pepino','zanahoria','aceite'],
    steps: ['Tuesta el pan.','Unta hummus.','Añade tomate, pepino y zanahoria.','Termina con aceite y sal.'] },
  { w: 5, day: 'Viernes', type: 'lunch', name: 'Merluza con arroz blanco',
    ing: ['merluza','arroz','ajo','limón','perejil','aceite'],
    steps: ['Cuece el arroz.','Cocina la merluza con ajo, limón y perejil.','Sirve el pescado con arroz.'] },
  { w: 5, day: 'Viernes', type: 'dinner', name: 'Huevos revueltos con tomate',
    ing: ['huevos','tomate','cebolla','aceite','pan'],
    steps: ['Sofríe cebolla y tomate.','Añade huevos batidos.','Remueve hasta cuajar.','Sirve con pan.'] },
  { w: 5, day: 'Sábado', type: 'lunch', name: 'Burrito de arroz, pollo y frijoles',
    ing: ['tortilla','arroz','pollo','alubias rojas','tomate','lechuga','queso','especias'],
    steps: ['Cocina el pollo con especias.','Calienta arroz y alubias.','Rellena la tortilla con todo.','Enrolla y dora en sartén.'] },
  { w: 5, day: 'Sábado', type: 'dinner', name: 'Ensalada griega sencilla',
    ing: ['tomate','pepino','cebolla','queso feta','aceitunas','aceite','orégano'],
    steps: ['Corta tomate, pepino y cebolla.','Añade queso y aceitunas.','Aliña con aceite, sal y orégano.'] },
  { w: 5, day: 'Domingo', type: 'lunch', name: 'Fideuá sencilla',
    ing: ['fideos','calamares','gambas','tomate','pimiento','caldo','aceite'],
    steps: ['Sofríe pimiento y tomate.','Añade calamares.','Incorpora fideos y caldo.','Cocina hasta que los fideos estén hechos.'] },
  { w: 5, day: 'Domingo', type: 'dinner', name: 'Crema de calabaza',
    ing: ['calabaza','zanahoria','patata','cebolla','aceite'],
    steps: ['Cuece todas las verduras.','Tritura con un poco de agua.','Añade aceite y sal al final.'] },

  // ── Semana 6 ──────────────────────────────────────────────────────────────
  { w: 6, day: 'Lunes', type: 'lunch', name: 'Arroz con atún y tomate',
    ing: ['arroz','atún','tomate','cebolla','pimiento','aceite'],
    steps: ['Cuece el arroz.','Sofríe cebolla y pimiento.','Añade tomate y atún.','Mezcla con el arroz.'] },
  { w: 6, day: 'Lunes', type: 'dinner', name: 'Tortilla de calabacín',
    ing: ['huevos','calabacín','cebolla','aceite'],
    steps: ['Saltea calabacín y cebolla.','Mezcla con huevos batidos.','Cuaja la tortilla.'] },
  { w: 6, day: 'Martes', type: 'lunch', name: 'Pollo salteado con noodles',
    ing: ['noodles','pollo','zanahoria','pimiento','cebolla','salsa de soja','aceite'],
    steps: ['Cuece los noodles.','Saltea pollo y verduras.','Añade salsa de soja.','Mezcla con los noodles.'] },
  { w: 6, day: 'Martes', type: 'dinner', name: 'Ensalada de lentejas',
    ing: ['lentejas','tomate','cebolla','zanahoria','huevo','aceite','vinagre'],
    steps: ['Lava las lentejas.','Cuece el huevo.','Mezcla con verduras y huevo troceado.','Aliña.'] },
  { w: 6, day: 'Miércoles', type: 'lunch', name: 'Pisto con huevo',
    ing: ['calabacín','berenjena','pimiento','cebolla','tomate','huevo','aceite'],
    steps: ['Sofríe cebolla y pimientos.','Añade calabacín, berenjena y tomate.','Cocina hasta que reduzca.','Sirve con huevo a la plancha.'] },
  { w: 6, day: 'Miércoles', type: 'dinner', name: 'Pescado al papillote',
    ing: ['pescado blanco','zanahoria','calabacín','cebolla','limón','aceite'],
    steps: ['Coloca pescado y verduras en papel de horno.','Añade limón, aceite y sal.','Cierra el paquete.','Hornea 15 minutos.'] },
  { w: 6, day: 'Jueves', type: 'lunch', name: 'Pasta con pesto y pollo',
    ing: ['pasta','pollo','pesto','tomate cherry','queso'],
    steps: ['Cuece la pasta.','Cocina el pollo en dados.','Mezcla pasta, pollo y pesto.','Añade tomate cherry y queso.'] },
  { w: 6, day: 'Jueves', type: 'dinner', name: 'Gazpacho con tostada de pavo',
    ing: ['tomate','pepino','pimiento','ajo','pan','pavo','aceite','vinagre'],
    steps: ['Tritura tomate, pepino, pimiento, ajo, aceite, vinagre y sal.','Enfría el gazpacho.','Tuesta pan y añade pavo.','Sirve junto.'] },
  { w: 6, day: 'Viernes', type: 'lunch', name: 'Garbanzos con bacalao',
    ing: ['garbanzos','bacalao','espinacas','cebolla','ajo','pimentón','aceite'],
    steps: ['Sofríe ajo y cebolla.','Añade pimentón, garbanzos y agua.','Incorpora espinacas y bacalao.','Cocina 10-15 minutos.'] },
  { w: 6, day: 'Viernes', type: 'dinner', name: 'Quesadillas de jamón y queso',
    ing: ['tortillas','jamón cocido','queso','tomate','lechuga'],
    steps: ['Rellena tortillas con jamón y queso.','Dóralas en sartén.','Acompaña con tomate y lechuga.'] },
  { w: 6, day: 'Sábado', type: 'lunch', name: 'Canelones de atún',
    ing: ['placas de canelón','atún','tomate','huevo','bechamel','queso rallado'],
    steps: ['Cuece las placas.','Mezcla atún, tomate y huevo cocido.','Rellena los canelones.','Cubre con bechamel y queso, y gratina.'] },
  { w: 6, day: 'Sábado', type: 'dinner', name: 'Ensalada de pollo y manzana',
    ing: ['pollo','lechuga','manzana','nueces','yogur','limón'],
    steps: ['Cocina el pollo y córtalo.','Mezcla lechuga, manzana y pollo.','Aliña con yogur, limón y sal.'] },
  { w: 6, day: 'Domingo', type: 'lunch', name: 'Conejo o pollo al ajillo',
    ing: ['pollo','ajo','vino blanco','patatas','aceite','perejil'],
    steps: ['Dora la carne con ajo.','Añade vino blanco y deja evaporar.','Cocina hasta que esté hecha.','Acompaña con patatas.'] },
  { w: 6, day: 'Domingo', type: 'dinner', name: 'Crema de espinacas',
    ing: ['espinacas','patata','cebolla','caldo','aceite'],
    steps: ['Cuece espinacas, patata y cebolla.','Tritura con caldo.','Ajusta de sal y sirve.'] },

  // ── Semana 7 ──────────────────────────────────────────────────────────────
  { w: 7, day: 'Lunes', type: 'lunch', name: 'Ensalada de quinoa con pollo',
    ing: ['quinoa','pollo','tomate','pepino','maíz','aceite','limón'],
    steps: ['Cuece la quinoa.','Cocina el pollo a la plancha.','Mezcla con verduras.','Aliña con aceite, limón y sal.'] },
  { w: 7, day: 'Lunes', type: 'dinner', name: 'Sopa de pollo con fideos',
    ing: ['caldo','pollo','zanahoria','puerro','fideos'],
    steps: ['Calienta el caldo con verduras.','Añade fideos.','Incorpora pollo desmenuzado.','Cocina hasta que los fideos estén listos.'] },
  { w: 7, day: 'Martes', type: 'lunch', name: 'Alubias pintas con arroz',
    ing: ['alubias pintas','arroz','cebolla','pimiento','tomate','pimentón'],
    steps: ['Sofríe verduras.','Añade tomate y pimentón.','Incorpora alubias y arroz cocido.','Cocina junto unos minutos.'] },
  { w: 7, day: 'Martes', type: 'dinner', name: 'Salmón a la plancha con ensalada',
    ing: ['salmón','lechuga','tomate','aguacate','limón','aceite'],
    steps: ['Cocina el salmón con sal y limón.','Prepara ensalada con lechuga, tomate y aguacate.','Aliña y sirve.'] },
  { w: 7, day: 'Miércoles', type: 'lunch', name: 'Espaguetis carbonara ligera',
    ing: ['espaguetis','huevo','queso','pavo','pimienta'],
    steps: ['Cuece los espaguetis.','Dora pavo.','Mezcla huevo batido con queso y pimienta.','Une todo fuera del fuego.'] },
  { w: 7, day: 'Miércoles', type: 'dinner', name: 'Verduras asadas con huevo',
    ing: ['berenjena','calabacín','pimiento','cebolla','huevo','aceite'],
    steps: ['Asa las verduras al horno.','Cocina un huevo a la plancha.','Sirve el huevo sobre las verduras.'] },
  { w: 7, day: 'Jueves', type: 'lunch', name: 'Pollo con salsa de yogur y patata',
    ing: ['pollo','yogur','limón','ajo','patata','aceite'],
    steps: ['Hornea o cuece la patata.','Cocina el pollo a la plancha.','Mezcla yogur, limón, ajo y sal.','Sirve el pollo con salsa y patata.'] },
  { w: 7, day: 'Jueves', type: 'dinner', name: 'Ensalada de tomate y sardinas',
    ing: ['tomate','sardinas en lata','cebolla','aceitunas','aceite'],
    steps: ['Corta tomate y cebolla.','Añade sardinas y aceitunas.','Aliña con aceite y sal.'] },
  { w: 7, day: 'Viernes', type: 'lunch', name: 'Risotto sencillo de champiñones',
    ing: ['arroz','champiñones','cebolla','caldo','queso rallado','aceite'],
    steps: ['Sofríe cebolla y champiñones.','Añade arroz y caldo poco a poco.','Remueve hasta que quede cremoso.','Añade queso al final.'] },
  { w: 7, day: 'Viernes', type: 'dinner', name: 'Bocadillo vegetal con huevo',
    ing: ['pan','huevo','lechuga','tomate','atún','aceite'],
    steps: ['Cuece o cocina el huevo.','Abre el pan y añade lechuga, tomate y huevo.','Añade atún opcional.','Aliña con aceite.'] },
  { w: 7, day: 'Sábado', type: 'lunch', name: 'Pollo teriyaki casero',
    ing: ['pollo','arroz','salsa de soja','miel','ajo','zanahoria','brócoli'],
    steps: ['Cuece el arroz.','Cocina el pollo en dados.','Añade soja, miel y ajo.','Sirve con verduras salteadas.'] },
  { w: 7, day: 'Sábado', type: 'dinner', name: 'Crepes salados de jamón y queso',
    ing: ['harina','huevo','leche','jamón','queso'],
    steps: ['Mezcla harina, huevo, leche y sal.','Haz crepes finos en sartén.','Rellena con jamón y queso.','Dobla y calienta hasta fundir.'] },
  { w: 7, day: 'Domingo', type: 'lunch', name: 'Merluza con patatas a la marinera',
    ing: ['merluza','patata','cebolla','ajo','caldo de pescado','perejil','aceite'],
    steps: ['Sofríe cebolla y ajo.','Añade patata en rodajas y caldo.','Cuando la patata esté tierna, añade merluza.','Cocina 8-10 minutos y añade perejil.'] },
  { w: 7, day: 'Domingo', type: 'dinner', name: 'Ensalada de queso fresco y frutos secos',
    ing: ['lechuga','queso fresco','tomate','nueces','manzana','aceite','vinagre'],
    steps: ['Lava la lechuga y corta tomate y manzana.','Añade queso fresco y nueces.','Aliña y sirve.'] },

  // ── Semana 8 ──────────────────────────────────────────────────────────────
  { w: 8, day: 'Lunes', type: 'lunch', name: 'Paella de verduras',
    ing: ['arroz','judías verdes','pimiento','tomate','caldo','cúrcuma','aceite'],
    steps: ['Sofríe las verduras.','Añade tomate y arroz.','Incorpora caldo y cúrcuma.','Cocina hasta que el arroz esté listo.'] },
  { w: 8, day: 'Lunes', type: 'dinner', name: 'Tortilla de atún',
    ing: ['huevos','atún','cebolla','aceite'],
    steps: ['Bate los huevos.','Añade atún escurrido y cebolla pochada.','Cuaja en sartén.'] },
  { w: 8, day: 'Martes', type: 'lunch', name: 'Pollo con pasta y verduras',
    ing: ['pasta','pollo','brócoli','zanahoria','cebolla','aceite'],
    steps: ['Cuece la pasta.','Saltea pollo y verduras.','Mezcla con la pasta.','Ajusta de sal y pimienta.'] },
  { w: 8, day: 'Martes', type: 'dinner', name: 'Crema fría de pepino y yogur',
    ing: ['pepino','yogur','ajo','limón','aceite'],
    steps: ['Pela y trocea el pepino.','Tritura con yogur, ajo, limón y sal.','Enfría antes de servir.','Añade aceite por encima.'] },
  { w: 8, day: 'Miércoles', type: 'lunch', name: 'Estofado de lentejas con verduras',
    ing: ['lentejas','zanahoria','patata','cebolla','pimiento','laurel','pimentón'],
    steps: ['Sofríe verduras.','Añade lentejas, patata, laurel y pimentón.','Cubre con agua.','Cocina hasta que estén tiernas.'] },
  { w: 8, day: 'Miércoles', type: 'dinner', name: 'Tostadas de queso y tomate',
    ing: ['pan','queso fresco','tomate','aceite','orégano'],
    steps: ['Tuesta el pan.','Añade tomate y queso.','Aliña con aceite, sal y orégano.'] },
  { w: 8, day: 'Jueves', type: 'lunch', name: 'Pescado con cuscús de verduras',
    ing: ['pescado blanco','cuscús','calabacín','zanahoria','cebolla','limón'],
    steps: ['Hidrata el cuscús.','Saltea verduras.','Cocina el pescado con limón.','Sirve pescado con cuscús y verduras.'] },
  { w: 8, day: 'Jueves', type: 'dinner', name: 'Ensalada César casera ligera',
    ing: ['lechuga','pollo','pan tostado','queso','yogur','limón'],
    steps: ['Cocina el pollo.','Mezcla yogur, limón y sal para la salsa.','Coloca lechuga, pollo, pan tostado y queso.','Añade salsa.'] },
  { w: 8, day: 'Viernes', type: 'lunch', name: 'Arroz con garbanzos y verduras',
    ing: ['arroz','garbanzos','espinacas','cebolla','tomate','pimentón','aceite'],
    steps: ['Cuece el arroz.','Sofríe cebolla, tomate y pimentón.','Añade garbanzos y espinacas.','Mezcla con arroz.'] },
  { w: 8, day: 'Viernes', type: 'dinner', name: 'Revuelto de pavo y queso',
    ing: ['huevos','pavo','queso','tomate','aceite'],
    steps: ['Bate los huevos.','Añade pavo troceado y queso.','Cuaja en sartén.','Acompaña con tomate.'] },
  { w: 8, day: 'Sábado', type: 'lunch', name: 'Ñoquis con tomate y mozzarella',
    ing: ['ñoquis','tomate','mozzarella','cebolla','aceite','orégano'],
    steps: ['Cuece los ñoquis.','Prepara salsa con cebolla y tomate.','Mezcla ñoquis con salsa.','Añade mozzarella y deja fundir.'] },
  { w: 8, day: 'Sábado', type: 'dinner', name: 'Ensalada de aguacate y langostinos',
    ing: ['aguacate','langostinos','lechuga','tomate','limón','aceite'],
    steps: ['Pela los langostinos.','Corta aguacate y tomate.','Mezcla con lechuga.','Aliña con limón, aceite y sal.'] },
  { w: 8, day: 'Domingo', type: 'lunch', name: 'Carne guisada con arroz',
    ing: ['ternera','arroz','zanahoria','cebolla','tomate','caldo','aceite'],
    steps: ['Dora la carne.','Añade verduras y tomate.','Cocina con caldo hasta que esté tierna.','Sirve con arroz blanco.'] },
  { w: 8, day: 'Domingo', type: 'dinner', name: 'Sopa de tomate',
    ing: ['tomate','cebolla','ajo','caldo','pan tostado','aceite'],
    steps: ['Sofríe cebolla y ajo.','Añade tomate y caldo.','Cocina 15 minutos y tritura.','Sirve con pan tostado.'] },

  // ── Semana 9 ──────────────────────────────────────────────────────────────
  { w: 9, day: 'Lunes', type: 'lunch', name: 'Pollo con garbanzos al curry',
    ing: ['pollo','garbanzos','cebolla','tomate','curry','leche de coco','aceite'],
    steps: ['Dora el pollo con cebolla.','Añade tomate y curry.','Incorpora garbanzos y leche.','Cocina hasta espesar.'] },
  { w: 9, day: 'Lunes', type: 'dinner', name: 'Ensalada de huevo y patata',
    ing: ['patata','huevo','atún','tomate','aceitunas','aceite'],
    steps: ['Cuece patata y huevo.','Trocea y mezcla con atún, tomate y aceitunas.','Aliña y sirve.'] },
  { w: 9, day: 'Martes', type: 'lunch', name: 'Tallarines con verduras',
    ing: ['tallarines','pimiento','zanahoria','cebolla','calabacín','salsa de soja','aceite'],
    steps: ['Cuece los tallarines.','Saltea las verduras en tiras.','Añade soja.','Mezcla con los tallarines.'] },
  { w: 9, day: 'Martes', type: 'dinner', name: 'Pescado al horno con ensalada',
    ing: ['pescado blanco','limón','ajo','lechuga','tomate','aceite'],
    steps: ['Hornea el pescado con ajo, limón y sal.','Prepara ensalada de lechuga y tomate.','Sirve junto.'] },
  { w: 9, day: 'Miércoles', type: 'lunch', name: 'Arroz a la cubana',
    ing: ['arroz','huevo','tomate frito','plátano','aceite'],
    steps: ['Cuece el arroz.','Cocina el huevo a la plancha.','Calienta tomate frito.','Sirve arroz con tomate, huevo y plátano.'] },
  { w: 9, day: 'Miércoles', type: 'dinner', name: 'Crema de verduras con picatostes',
    ing: ['verduras variadas','patata','caldo','pan','aceite'],
    steps: ['Cuece verduras y patata.','Tritura con caldo.','Tuesta pan en dados.','Sirve la crema con picatostes.'] },
  { w: 9, day: 'Jueves', type: 'lunch', name: 'Ensalada completa de alubias',
    ing: ['alubias','tomate','cebolla','pimiento','huevo','atún','aceite','vinagre'],
    steps: ['Lava las alubias.','Cuece el huevo.','Mezcla con verduras, atún y huevo.','Aliña.'] },
  { w: 9, day: 'Jueves', type: 'dinner', name: 'Rollitos de tortilla con pavo',
    ing: ['huevos','pavo','queso crema','lechuga','tomate'],
    steps: ['Haz una tortilla fina.','Unta queso crema.','Añade pavo, lechuga y tomate.','Enrolla y corta.'] },
  { w: 9, day: 'Viernes', type: 'lunch', name: 'Salmón con puré de patata',
    ing: ['salmón','patata','leche','mantequilla','limón'],
    steps: ['Cuece patatas y machácalas con leche y sal.','Cocina el salmón con limón.','Sirve salmón con puré.'] },
  { w: 9, day: 'Viernes', type: 'dinner', name: 'Champiñones rellenos',
    ing: ['champiñones','jamón','queso','ajo','perejil','aceite'],
    steps: ['Limpia los champiñones y retira el tallo.','Mezcla jamón, queso, ajo y perejil.','Rellena los champiñones.','Hornea hasta dorar.'] },
  { w: 9, day: 'Sábado', type: 'lunch', name: 'Pasta gratinada con verduras',
    ing: ['pasta','calabacín','berenjena','tomate','queso rallado','aceite'],
    steps: ['Cuece la pasta.','Saltea las verduras con tomate.','Mezcla con la pasta.','Gratina con queso.'] },
  { w: 9, day: 'Sábado', type: 'dinner', name: 'Ensalada de pollo crujiente',
    ing: ['pollo','lechuga','tomate','pan rallado','huevo','yogur','limón'],
    steps: ['Reboza el pollo con huevo y pan rallado.','Hornea o cocina en sartén.','Prepara ensalada.','Añade salsa de yogur y limón.'] },
  { w: 9, day: 'Domingo', type: 'lunch', name: 'Cocido sencillo',
    ing: ['garbanzos','pollo','zanahoria','patata','repollo','fideos'],
    steps: ['Cuece garbanzos con pollo y verduras.','Separa caldo y añade fideos.','Sirve primero sopa y después garbanzos con carne.'] },
  { w: 9, day: 'Domingo', type: 'dinner', name: 'Tostas de atún y pimiento',
    ing: ['pan','atún','pimiento asado','tomate','aceite'],
    steps: ['Tuesta el pan.','Añade tomate, atún y pimiento.','Aliña con aceite y sal.'] },

  // ── Semana 10 ─────────────────────────────────────────────────────────────
  { w: 10, day: 'Lunes', type: 'lunch', name: 'Ensalada de arroz con pollo',
    ing: ['arroz','pollo','tomate','maíz','zanahoria','huevo','aceite'],
    steps: ['Cuece arroz y huevo.','Cocina pollo en dados.','Mezcla con tomate, maíz y zanahoria.','Aliña.'] },
  { w: 10, day: 'Lunes', type: 'dinner', name: 'Crema de brócoli',
    ing: ['brócoli','patata','cebolla','caldo','queso','aceite'],
    steps: ['Cuece brócoli, patata y cebolla.','Tritura con caldo.','Añade queso opcional al final.'] },
  { w: 10, day: 'Martes', type: 'lunch', name: 'Albóndigas de pollo con arroz',
    ing: ['pollo picado','huevo','pan rallado','ajo','tomate','arroz','aceite'],
    steps: ['Mezcla carne, huevo, ajo y pan rallado.','Forma albóndigas y dóralas.','Cocina con tomate triturado.','Sirve con arroz cocido.'] },
  { w: 10, day: 'Martes', type: 'dinner', name: 'Ensalada de queso de cabra',
    ing: ['lechuga','queso de cabra','tomate','nueces','manzana','aceite','vinagre'],
    steps: ['Lava y corta la lechuga.','Añade tomate, manzana, queso y nueces.','Aliña y sirve.'] },
  { w: 10, day: 'Miércoles', type: 'lunch', name: 'Pescado con patatas panadera',
    ing: ['pescado blanco','patata','cebolla','pimiento','limón','aceite'],
    steps: ['Hornea patata, cebolla y pimiento en rodajas.','Añade el pescado encima.','Hornea 10-12 minutos más.','Sirve con limón.'] },
  { w: 10, day: 'Miércoles', type: 'dinner', name: 'Huevos al plato',
    ing: ['huevos','tomate','guisantes','jamón','queso'],
    steps: ['Coloca tomate en una cazuela pequeña.','Añade guisantes y jamón.','Casca los huevos encima.','Hornea hasta que cuajen.'] },
  { w: 10, day: 'Jueves', type: 'lunch', name: 'Garbanzos con verduras asadas',
    ing: ['garbanzos','calabacín','berenjena','pimiento','cebolla','aceite','comino'],
    steps: ['Asa las verduras al horno.','Calienta los garbanzos.','Mezcla todo con comino y aceite.','Ajusta de sal.'] },
  { w: 10, day: 'Jueves', type: 'dinner', name: 'Wrap de salmón ahumado',
    ing: ['tortilla','salmón ahumado','queso crema','lechuga','pepino','limón'],
    steps: ['Unta queso crema en la tortilla.','Añade salmón, lechuga y pepino.','Añade limón.','Enrolla.'] },
  { w: 10, day: 'Viernes', type: 'lunch', name: 'Pasta con pollo y salsa de tomate',
    ing: ['pasta','pollo','tomate','cebolla','queso','aceite','orégano'],
    steps: ['Cuece la pasta.','Dora pollo con cebolla.','Añade tomate y orégano.','Mezcla con pasta y queso.'] },
  { w: 10, day: 'Viernes', type: 'dinner', name: 'Revuelto de verduras',
    ing: ['huevos','calabacín','pimiento','cebolla','champiñones','aceite'],
    steps: ['Saltea las verduras.','Añade huevos batidos.','Remueve hasta cuajar.'] },
  { w: 10, day: 'Sábado', type: 'lunch', name: 'Arroz negro sencillo',
    ing: ['arroz','calamares','tinta de calamar','cebolla','tomate','caldo de pescado','aceite'],
    steps: ['Sofríe cebolla y tomate.','Añade calamares.','Incorpora arroz, tinta y caldo.','Cocina hasta que el arroz esté hecho.'] },
  { w: 10, day: 'Sábado', type: 'dinner', name: 'Mini pizzas de pan',
    ing: ['pan','tomate','queso','pavo','champiñones','orégano'],
    steps: ['Pon tomate sobre rebanadas de pan.','Añade queso y toppings.','Hornea hasta fundir.','Sirve calientes.'] },
  { w: 10, day: 'Domingo', type: 'lunch', name: 'Pollo en salsa con verduras',
    ing: ['pollo','cebolla','zanahoria','champiñones','caldo','aceite'],
    steps: ['Dora el pollo.','Añade verduras y rehoga.','Cubre con caldo.','Cocina hasta que el pollo esté tierno.'] },
  { w: 10, day: 'Domingo', type: 'dinner', name: 'Ensalada templada de patata y salmón',
    ing: ['patata','salmón ahumado','huevo','lechuga','aceite','limón'],
    steps: ['Cuece patata y huevo.','Coloca una base de lechuga.','Añade patata, huevo y salmón.','Aliña con aceite, sal y limón.'] },
];

function seedMenus() {
  const db = getDb();

  const existing = db.prepare('SELECT COUNT(*) as n FROM weekly_menus').get();
  if (existing.n > 0) {
    console.log(`Weekly menus already seeded (${existing.n} found). Skipping.`);
    return;
  }

  const insert = db.prepare(
    `INSERT INTO weekly_menus (week_number, day_name, meal_type, recipe_name, ingredients, steps)
     VALUES (?, ?, ?, ?, ?, ?)`
  );

  db.exec('BEGIN');
  try {
    for (const m of WEEKLY_MENUS) {
      insert.run(m.w, m.day, m.type, m.name, JSON.stringify(m.ing), JSON.stringify(m.steps));
    }
    db.exec('COMMIT');
  } catch (err) {
    db.exec('ROLLBACK');
    throw err;
  }

  console.log(`Seeded ${WEEKLY_MENUS.length} weekly menu entries.`);
}

seedMenus();
